### PR TITLE
Added 1.21 Items and Updated to Minecraft 1.21

### PR DESCRIPTION
**Pull request by XCraftTM**
After your Project has been off for a while now i wanted to update it again to the newest version. I tried to keep the structure the same as it was before but updated it to only work on 1.21 and above. This was required to allow everything to work smoothly... you can also update the spigotmc page with the update

### CODE REVIEW

**Comment by Duckulus** [comment]
thank you very much, this is very awesome!!

I wanted to update this for a while but I never had the time to do it, I really appreciate it!

Did you write some sort of script to generate all the images? If yes you can also add it to the repo to make future updates easier.

**Comment by XCraftTM** [comment]
I actually made a small NodeJS Script which generates me the lines of code which i need to add and then also used the same script and api to save all the images from the official minecraft assets. I can share a ZIP file to the Script here if you want

**Comment by XCraftTM** [comment]
[itemtesting.zip](https://github.com/user-attachments/files/17269041/itemtesting.zip)
Here i attached the Zip file with the Script... there is a readme which explaines everything.

**Comment by Duckulus** [comment]
looks awesome, I'll add it to the repo if you don't mind?

**Comment by XCraftTM** [comment]
Yeah sure! Everything i make doesn't have any copyright stuff so you can reuse anything i make without any issues

**Comment by Duckulus** [comment]
great, then just take care of the 2 little things I mentioned in the review and I'll merge this

**Pull request merged**
